version: "2.4"

services:
  acorn_vehicle:
    extends:
      file: docker-compose-vehicle.yml
      service: acorn_vehicle
    volumes:
      - .:/home/acorn/
      - ./.bashrc:/home/acorn/.bashrc
    command: bash -c /home/acorn/vehicle/autolaunch_vehicle_sim.sh
    ipc: host
  acorn_server:
    extends:
      file: docker-compose-server.yml
      service: acorn_server
