version: "3.7"

services:
  acorn_vehicle:
    extends:
      file: docker-compose-vehicle.yml
      service: acorn_vehicle
    volumes:
      - .:/home/pi/
      - ./.bashrc:/home/pi/.bashrc
    command: sh -c /home/pi/vehicle/autolaunch_vehicle_sim.sh
    ipc: host
  acorn_server:
    extends:
      file: docker-compose-server.yml
      service: acorn_server
