name: test

on: [pull_request, push, workflow_dispatch]

concurrency:
  group: test-${{github.ref}}
  cancel-in-progress: true

jobs:
  # image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout source
  #       uses: actions/checkout@v2
  #
  #     - name: push image
  #       run: GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} make push-image
  #
  test:
    runs-on: ubuntu-latest
    # To create and push new image: make push-image
    container: ghcr.io/twisted-fields/acorn_docker:latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run tests
        run: coverage run -m pytest

      - name: Workaround for codecov issue 263
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
